name: meals_app
description: A simple Flutter app that uses TheMealDB API to show recipes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter

  http: ^1.2.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.6

  cloud_firestore: ^5.4.4

  
  firebase_messaging: ^15.1.2

  
  flutter_local_notifications: ^17.2.1

  firebase_auth: ^5.1.4

  timezone: ^0.9.2
  
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
